gazebo_ros_control:
  pid_gains:
    gripper_joint_1:
      p: 50.0
    gripper_joint_1_1:
      p: 50.0
    gripper_joint_0_1:
      p: 50.0
    flipper_joint_0:
      p: 1000.0
      i: 0.0
      d: 0.0
    left_flipper_joint:
      p: 1000.0
      i: 0.0
      d: 0.0